name: Build & Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    tags:
      - '*'
  workflow_dispatch:
    # Allow to run manually

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: ${{ matrix.os }} with python ${{ matrix.python-version }}
    runs-on: ${{ matrix.runs_on || matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-15-intel', 'macos-latest', 'darwin-27', 'ubuntu-latest', 'windows-latest', 'ubuntu-24.04-arm']
        python-version: ['3.13', '3.14', '3.14t', '3.15']
        include:
          - os: darwin-27
            runs_on:
              group: sage-darwin27
              labels: darwin-27
    steps:
    - name: Set up the repository
      uses: actions/checkout@v6
      with:
          submodules: recursive
          fetch-depth: 0
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
    - name: Build
      run: |
        uv sync --frozen --inexact -v --no-install-project
        uv sync --frozen --inexact -v --no-build-isolation --no-editable --reinstall-package cysignals --config-settings=builddir=builddir
    - name: Install cypari2
      run: |
        sudo apt-get update
        sudo apt-get install pari-gp libpari-dev
        pip install --upgrade cypari2
      if: matrix.os == 'ubuntu-latest'
    - name: Test
      run: uv run --no-editable meson test --print-errorlogs -C builddir
